apache/maven-enforcer

- maven-enforcer-plugin/src/site/apt/examples/check-specific-rule-via-cli.apt.vm
- maven-enforcer-plugin/src/site/site.xml
Introduce an example site with example "check specific rule via cli"
> [MENFORCER-142] documentation - add example for checking rules via cli

- enforcer-rules/src/site/apt/dependencyConvergence.apt.vm
> fixed typo in dependencyConvergence.html

- maven-enforcer-plugin/src/it/mrm/repository/menforcer269_project-higher-1.0.0.pom
- maven-enforcer-plugin/src/it/mrm/repository/menforcer269_project-lower-1.0.0.pom
- maven-enforcer-plugin/src/it/mrm/repository/menforcer269_project-middle-1.0.0.pom
- maven-enforcer-plugin/src/it/projects/dependencies_converge_exclude_wildcard/invoker.properties
- maven-enforcer-plugin/src/it/projects/dependencies_converge_exclude_wildcard/pom.xml
- maven-enforcer-plugin/src/it/projects/require-upper-bound-exclude_wildcard/invoker.properties
- maven-enforcer-plugin/src/it/projects/require-upper-bound-exclude_wildcard/pom.xml
[MENFORCER-195] [MENFORCER-269] Added tests to validate wildcard support for DependencyConvergence and RequireUpperBound with MNG-6713 (https://github.com/apache/maven/pull/269)
[Individual Contributor …
> [MENFORCER-195] [MENFORCER-269] Added tests to validate wildcard support

- enforcer-rules/src/site/apt/requireEnvironmentVariable.apt.vm
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
> (doc) Fix parameter name

- README.md
I'm assuming that the following list does not apply in the case of a minor text change to the README.
------------------------------------------------------------------------------------------------------ …
> Corrects the recommended plugin version in the README (update from 3.0.0-M2 to 3.0.0-M3)

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireSnapshotVersion.java
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_failure_parent-ci-friendly/invoker.properties
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_failure_parent-ci-friendly/module/pom.xml
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_failure_parent-ci-friendly/pom.xml
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_failure_parent-ci-friendly/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_success_parent-ci-friendly/invoker.properties
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_success_parent-ci-friendly/module/pom.xml
- maven-enforcer-plugin/src/it/projects/require-snapshot-version_success_parent-ci-friendly/pom.xml
Fixes unresolved `${revision}` parent version.
I am not sure whether this is the best approach.
`project.getParentArtifact()` not providing the resolved version might also be considered a Maven core bug.
for the change (usually before you start working on it).  Trivial changes like typos do not
require a JIRA issue.  Your pull request should address just this issue, without
is to use the JIRA issue title in the pull request title and in the first line of the …
> [MENFORCER-346] - RequireSnapshotVersion: Fix parent with CI Friendly Version

- .github/workflows/maven.yml
> enable GitHub Actions CI

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanDuplicatePomDependencyVersions.java
- maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/invoker.properties
- maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/pom.xml
- maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/verify.groovy
really check dependencyManagement section
> [MENFORCER-301] check dependencyManagement

- pom.xml
@michael-o last version that supports Java 7
> update commons IO

- .gitignore
> Remove duplicate .gitignore lines

- pom.xml
> [MENFORCER-379] - Update maven-common-artifact-filters to 3.1.1

- enforcer-api/src/main/assembly/custom-rule-sample.xml
- maven-enforcer-plugin/src/it/projects/resolve_collect_dependencies/pom.xml
- maven-enforcer-plugin/src/it/projects/resolve_collect_dependencies/src/assembly/extjars.xml
> [MENFORCER-380] - update assembly links

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractVersionEnforcer.java
use containsVersion from VersionRange instead of Restriction
> simplify code

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractVersionEnforcer.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/ReactorModuleConvergence.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireFileChecksum.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireUpperBoundDeps.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/BannedDependenciesTestSetup.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/ReactorModuleConvergenceTest.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/RequireActiveProfileTest.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestAlwaysFail.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestAlwaysPass.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestMavenVersion.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFileChecksum.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFilesDontExist.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFilesExist.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFilesSize.java
> fix assorted warnings and deprecations

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireUpperBoundDeps.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/EnforcerTestUtils.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/RequireUpperBoundDepsTest.java
> [MENFORCER-381] include classifiers in error messages

- README.md
> Update latest release

- enforcer-rules/src/site/apt/reactorModuleConvergence.apt.vm
Fixes typo in 'multi-module'
please ask on the developers …
> (doc) - Reactor Module Convergence web page improvements

- enforcer-rules/src/site/apt/requireFilesSize.apt.vm
Adds periods to end of parameter descriptions to be consistent with full parameter list
[Individual Contributor License …
> (doc) - Require Fires Size page improvements

- enforcer-rules/src/site/apt/requireNoRepositories.apt.vm
Fixes typo in 'November'
please ask on the developers …
> (doc) - Require No Repositories page improvements

- enforcer-rules/src/site/apt/requireJavaVersion.apt.vm
Fixes typo in 'preceding'
please ask on the developers …
> (doc) - Require Java Version web page improvements

- .github/workflows/maven-verify.yml
> [MENFORCER-404] Shared GitHub Actions

- enforcer-rules/src/site/apt/index.apt
> [MENFORCER-361] Add link to newly introduced rule to index

- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
> Fix javadoc of "fail" parameter

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanDependencyManagementScope.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/ArtifactMatcher.java
- enforcer-rules/src/site/apt/banDependencyManagementScope.apt.vm
- enforcer-rules/src/site/apt/index.apt
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/BanDependencyManagementScopeTest.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/utils/TestArtifactMatcher.java
- maven-enforcer-plugin/src/it/projects/ban-dependency-management-scope-fail/invoker.properties
- maven-enforcer-plugin/src/it/projects/ban-dependency-management-scope-fail/pom.xml
- maven-enforcer-plugin/src/it/projects/ban-dependency-management-scope-fail/verify.groovy
dependencyManagement
To make clear that you license your …
> [MENFORCER-424] add enforcer rule which bans scope from

- enforcer-rules/pom.xml
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractVersionEnforcer.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVersion.java
- enforcer-rules/src/site/apt/requireJavaVersion.apt.vm
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVersion.java
> [MENFORCER-440] Allow 8 as JDK version for requireJavaVersion

- maven-enforcer-plugin/src/it/projects/banned-plugins-fails/invoker.properties
- maven-enforcer-plugin/src/it/projects/banned-plugins-fails/pom.xml
- maven-enforcer-plugin/src/it/projects/banned-plugins-fails/verify.groovy
> Add test for confirmation of failed bannedPlugins

- enforcer-rules/pom.xml
- maven-enforcer-plugin/pom.xml
- pom.xml
> [MENFORCER-435] Remove not needed maven-dependency-tree and maven-compat

- src/site/xdoc/download.xml.vm
> [MENFORCER-451] Refresh download page

- enforcer-rules/pom.xml
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EnforcerRuleDesc.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EnforcerRuleManager.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EnforcerRuleManagerException.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/EnforcerRuleManagerTest.java
- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
- maven-enforcer-plugin/src/test/java/org/apache/maven/plugins/enforcer/TestEnforceMojo.java
> [MENFORCER-453] Mange rules configuration by plugin

- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
Just a small clean-up to avoid dealing with arrays.
To make clear …
> [MENFORCER-431] Clean-up - use List<String> instead of String[]

- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BannedDependenciesBase.java
- enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireReleaseDeps.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/BannedDependenciesTestSetup.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/EnforcerTestUtils.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/RequireUpperBoundDepsTest.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestBannedDependencies.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireReleaseDeps.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/utils/DependencyNodeBuilder.java
- enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/utils/EnforcerRuleUtilsHelper.java
> MENFORCER-435: Fixing unit tests

- maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/module1/pom.xml
- maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/module2/pom.xml
- maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/pom.xml
- maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/verify.groovy
Also cover MENFORCER-437
---
To make clear that you license your …
> [MENFORCER-407] Regression for dependencyConvergence - transitive provided

- maven-enforcer-plugin/src/it/projects/non-exeisting-optional-dependency/pom.xml
- maven-enforcer-plugin/src/it/projects/non-exeisting-optional-dependency/verify.groovy
> [MENFORCER-378] Regression for non existing optional dependency

- maven-enforcer-plugin/src/it/projects/MENFORCER-434/invoker.properties
- maven-enforcer-plugin/src/it/projects/MENFORCER-434/pom.xml
- maven-enforcer-plugin/src/it/projects/MENFORCER-434/verify.groovy
> [MENFORCER-434] Regression bannedDependencies - matching with not existing versions

- maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/invoker.properties
- maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version-utf8-with-bom/invoker.properties
- maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version/invoker.properties
- maven-enforcer-plugin/src/it/projects/require-plugin-versions-expressions2/pom.xml
- maven-enforcer-plugin/src/it/projects/require-profile-ids-exist_failure/invoker.properties
Maven 4 strict checking such rules, so build will not start with projects contains such violations.
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
> [MENFORCER-447] Skip tests for banDuplicatePomDependencyVersions and requireProfileIdsExist with Maven 4

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireNoRepositories.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireNoRepositories.java
- maven-enforcer-plugin/src/it/projects/require-no-repositories/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-no-repositories_mm/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-no-repositories_mm_ci/verify.groovy
Maven 4 model contains repositories defined in settings.xml
As workaround we exclude repositories defined in settings.xml
---
[Individual Contributor License …
> [MENFORCER-447] RequireNoRepositories skip repositories defined in settings.xml

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireOS.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/utils/OSUtil.java
- enforcer-rules/src/site/apt/requireOS.apt.vm
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireOS.java
- maven-enforcer-plugin/src/it/projects/require-os/pom.xml
- maven-enforcer-plugin/src/it/projects/require-os/verify.groovy
- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/DisplayInfoMojo.java
> [MENFORCER-458] Move RequireOS to new API

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/AbstractRequireFiles.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/RequireFilesDontExist.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/RequireFilesExist.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/RequireFilesSize.java
- enforcer-rules/src/site/apt/requireFilesDontExist.apt.vm
- enforcer-rules/src/site/apt/requireFilesExist.apt.vm
- enforcer-rules/src/site/apt/requireFilesSize.apt.vm
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/files/TestRequireFilesDontExist.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/files/TestRequireFilesExist.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/files/TestRequireFilesSize.java
- maven-enforcer-plugin/src/it/projects/require-files-dont-exist/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-files-exist/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-files-size/verify.groovy
> [MENFORCER-458] Move RequireFiles* to new API

- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
In multimodal project it is very difficult to find a reason of failed job.
---
please ask on the …
> [MENFORCER-415] Move error message to MojoException

- maven-enforcer-plugin/src/it/projects/always-pass/verify.groovy
- maven-enforcer-plugin/src/it/projects/ban-distribution-management/verify.groovy
- maven-enforcer-plugin/src/it/projects/dependency-convergence_transitive_provided/verify.groovy
- maven-enforcer-plugin/src/it/projects/evaluate-beanshell/verify.groovy
- maven-enforcer-plugin/src/it/projects/external-rules-always-pass/verify.groovy
- maven-enforcer-plugin/src/it/projects/non-exeisting-optional-dependency/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-environment-variable/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-file-checksum/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-files-dont-exist/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-files-exist/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-files-size/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-java-vendor-multi-module/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-java-version/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-maven-version/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-no-repositories/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-no-repositories_mm/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-no-repositories_mm_ci/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-os/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-property/verify.groovy
- maven-enforcer-plugin/src/it/projects/require-textfile-checksum/verify.groovy
- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
- maven-enforcer-plugin/src/test/java/org/apache/maven/plugins/enforcer/TestEnforceMojo.java
> [MENFORCER-463] Change success message from executed to passed

- enforcer-rules/src/site/apt/banDynamicVersions.apt.vm
Name in the "ignores" element's end-tag must match the name in the start-tag.
please ask on the …
> (doc) fix banDynamicVersions example

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/DependencyConvergence.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/selector/AllLevelsScopeDependencySelector.java
- enforcer-rules/src/site/apt/dependencyConvergence.apt.vm
- maven-enforcer-plugin/src/it/projects/dependency-convergence_excludedScopes/invoker.properties
- maven-enforcer-plugin/src/it/projects/dependency-convergence_excludedScopes/pom.xml
- maven-enforcer-plugin/src/it/projects/dependency-convergence_excludedScopes/verify.groovy
> [MENFORCER-470] Configurable scopes for DependencyConvergence rule - refactor

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BanDuplicatePomDependencyVersions.java
- maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/verify.groovy
- maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version-utf8-with-bom/verify.groovy
- maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version/verify.groovy
> [MENFORCER-465] Remove superfluous blanks in BanDuplicatePomDependencyVersions

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDeps.java
- enforcer-rules/src/site/apt/requireUpperBoundDeps.apt.vm
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDepsTest.java
- maven-enforcer-plugin/src/it/mrm/repository/menforcer138_container-default-1.0-alpha-9-stable-1.pom
- maven-enforcer-plugin/src/it/mrm/repository/menforcer138_utils-1.0.4.pom
- maven-enforcer-plugin/src/it/projects/require-upper-bound-dependencies-scope-change/invoker.properties
- maven-enforcer-plugin/src/it/projects/require-upper-bound-dependencies-scope-change/pom.xml
- maven-enforcer-plugin/src/it/projects/require-upper-bound-dependencies-scope-change/verify.groovy
> [MENFORCER-276] Allow ignoring dependency scopes in RequireUpperBoundDeps

- maven-enforcer-extension/pom.xml
We need use extraArtifacts to be sure that plugin is installed for ITs
---
please ask on the …
> [MENFORCER-472] Install maven-enforcer-plugin for ITs in maven-enforcer-extension

- maven-enforcer-plugin/src/it/projects/dependencies_converge/pom.xml
> [MENFORCER-393] Extend IT for dependencyConvergence and no standard protocol in repository

- pom.xml
> [MENFORCER-487] Bump commons-codec from 1.15 to 1.16.0

- pom.xml
> [MENFORCER-489] Bump commons-lang3 from 3.12.0 to 3.13.0

- maven-enforcer-plugin/pom.xml
The new maven-plugin-report-plugin should be used.
---
To make …
> [MENFORCER-491] Fix plugin documentation generation

- enforcer-api/pom.xml
- enforcer-rules/pom.xml
- maven-enforcer-extension/pom.xml
- maven-enforcer-plugin/pom.xml
- pom.xml
> [MENFORCER-492] Bump plexus-utils from 3.5.1 to 4.0.0 and plexus-xml 3.0.0

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireOS.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireOS.java
https://issues.apache.org/jira/browse/MENFORCER-503
> [MENFORCER-503] Pass context to ProfileActivator - fix NPE in Maven 3.9.7

- enforcer-rules/src/site/apt/requireMatchingCoordinates.apt.vm
> [MENFORCER-505] fix documentation for requireMatchingCoordinates

- enforcer-api/pom.xml
- enforcer-rules/pom.xml
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java
- enforcer-rules/src/site/apt/requireSameVersions.apt.vm
- maven-enforcer-extension/pom.xml
- maven-enforcer-plugin/pom.xml
- maven-enforcer-plugin/src/it/projects/require-same-versions_multi-module-build/invoker.properties
- maven-enforcer-plugin/src/it/projects/require-same-versions_multi-module-build/module1/pom.xml
- maven-enforcer-plugin/src/it/projects/require-same-versions_multi-module-build/module2/pom.xml
- maven-enforcer-plugin/src/it/projects/require-same-versions_multi-module-build/pom.xml
- maven-enforcer-plugin/src/it/projects/require-same-versions_multi-module-build/verify.groovy
- pom.xml
> [MENFORCER-508] Add option to enforce same versions among Maven modules

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequirePluginVersions.java
> return not needed

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BanDependencyManagementScope.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BannedRepositories.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/ExternalRules.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/ReactorModuleConvergence.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequirePluginVersions.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanDynamicVersions.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/RequireFilesExist.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/utils/ArtifactMatcher.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/version/RequireJavaVersion.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/BanDistributionManagementTest.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestAlwaysPass.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireJavaVendor.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequirePluginVersions.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/utils/TestArtifactMatcher.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/version/TestAbstractVersionEnforcer.java
- maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
There are also some likely bugs it pulled out, but I'll check those in another PR.
> A grabbag of small simplifications found by IntelliJ

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BanDuplicatePomDependencyVersions.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireReleaseDepsTest.java
> Remove commented code

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/RequireFilesDontExist.java
- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/files/RequireFilesExist.java
Minor improvement IntelliJ suggested
> Simplify control flow

- .github/workflows/pr-automation.yml
- .github/workflows/release-drafter.yml
- .github/workflows/stale.yml
> Add GitHub Automation actions

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/checksum/RequireTextFileChecksum.java
- enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/checksum/TestRequireTextFileChecksum.java
> Use cached default charset and update URL fragment

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BannedRepositories.java
A few less objects created at runtime. Performance impact is likely not measurable, but the code gets smaller and easier to read, which is.
> Eliminate some string operations

- .github/ISSUE_TEMPLATE/BUG.yml
- .github/ISSUE_TEMPLATE/FEATURE.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/pull_request_template.md
- .github/release-drafter.yml
- README.md
- pom.xml
* Release was already there
* Milestone was already there
* Updated PR-Template to new one
> Enable Github Issues

- enforcer-api/src/site/apt/writing-a-custom-rule.apt.vm
Resolves #369 
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
> Make documentation explicit about java versions for custom rules

- enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/utils/ParentsVisitor.java
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
> Fixes #920 - Remove usage of Stack
