maven-enforcer-plugin/src/site/apt/index.apt
@khmarbaise Java 8 is now required and plugin is at M3. Let's just remove this section that seems to go out of date and isn't really needed here.
=> Remove obsolete section

.gitignore, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequirePluginVersions.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/EnforcerRuleUtils.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequirePluginVersions.java
@khmarbaise Something I found while trying, and failing, to upgrade this to Maven 3.1. I think artifactFactory in EnforcerRuleUtils is unused, and the tests pass, but perhaps there's some weird class loading implication?
=> remove unused, deprecated field

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EvaluateBeanshell.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestEvaluateBeanshell.java
The Beanshell interpreter in EvaluateBeanShell was a static field, but this object is not thread safe. I wrapped the BeanShell interpreter in a ThreadLocal. The alternative would be to create a new Interpreter on each invocation, but I don't know how expensive the Interpreter object is. Using ThreadLocal is probably closer to the original design where it was a singleton. 
I added a (somewhat naive) unit test that failed on every run on my old 4 core mac, and ran green with the new ThreadLocal variant. However I am not sure if this is the correct way to test this, or how this will behave on other hardware. 
for the change (usually before you start working on it).  Trivial changes like typos do not …
=> [MENFORCER-336] - Fixes race condition in EvaluateBeanshell

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractBanDependencies.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanTransitiveDependencies.java, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies/invoker.properties, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies/module1/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies/module2/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies_failure/invoker.properties, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies_failure/module1/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies_failure/module2/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies_failure/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies_failure/verify.groovy, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude/invoker.properties, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude/module1/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude/module2/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude_failure/invoker.properties, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude_failure/module1/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude_failure/module2/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude_failure/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude_failure/verify.groovy, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-snapshot-parent_failure/invoker.properties, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-snapshot-parent_failure/module1/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-snapshot-parent_failure/module2/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-snapshot-parent_failure/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-snapshot-parent_failure/verify.groovy, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies/invoker.properties, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies/module1/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies/module2/pom.xml, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies/pom.xml
see [https://issues.apache.org/jira/browse/MENFORCER-304](https://issues.apache.org/jira/browse/MENFORCER-304)
=>  [MENFORCER-304] - Improve dependency resolving in multiple modules project

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireProfileIdsExist.java, enforcer-rules/src/site/apt/requireProfileIdsExist.apt.vm
Fixes RequireProfileIdsExist behavior if there are no profiles on the command line nor in the pom.xml. Fixes breadcrumbs on the plugin's site for the RequireProfileIdsExist rule page.
I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
=> [MENFORCER-320] RequireProfileIdsExist check must not fail if no profiles are used

pom.xml
Upgrading to Extra Enforcer Rules 1.3, so Maven Enforcer Plugin could support Java 13, 14 and 15.
=> Support for Java 13, 14 and 15 using Extra Enforcer Rules 1.3

enforcer-rules/src/site/apt/requireOS.apt.vm
=> (doc) - Require OS web page improvements

maven-enforcer-plugin/src/it/projects/ban-distribution-management-multi-module-build/verify.groovy, maven-enforcer-plugin/src/it/projects/ban-duplicate-dependencies-versions/verify.groovy, maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version-utf8-with-bom/verify.groovy, maven-enforcer-plugin/src/it/projects/ban-pom-dependency-version/verify.groovy, maven-enforcer-plugin/src/it/projects/ban-transitive-dependencies-fail/verify.groovy, maven-enforcer-plugin/src/it/projects/banned-dependencies-versionrange-fail/verify.groovy, maven-enforcer-plugin/src/it/projects/require-no-repositories-allow-plugin-repo/verify.groovy, maven-enforcer-plugin/src/it/projects/require-no-repositories-allow-repo/verify.groovy, maven-enforcer-plugin/src/it/projects/require-no-repositories_failure/verify.groovy, maven-enforcer-plugin/src/it/projects/require-no-repositories_failure_allowed-plugin-repo/verify.groovy, maven-enforcer-plugin/src/it/projects/require-no-repositories_failure_plugin-repositories/verify.groovy, maven-enforcer-plugin/src/it/projects/require-no-repositories_failure_repositories/verify.groovy, maven-enforcer-plugin/src/it/projects/require-plugin-versions-ci/verify.groovy, maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
=> [MENFORCER-409] Log at ERROR level when <fail> is set

maven-enforcer-extension/pom.xml, maven-enforcer-plugin/pom.xml, pom.xml, src/site/site.xml
- use plugins versions and configurations from parent
- use site config from parent
- maven core artifacts in provided scope in plugin
---
[Individual Contributor License …
=> [MENFORCER-418] Upgrade Parent to 36

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireUpperBoundDeps.java, pom.xml
=> [MENFORCER-419] Upgrade Maven to 3.2.5

enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/EnforcerRuleHelper.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractBanDependencies.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/DefaultEnforcementRuleHelper.java
=> [MENFORCER-420] cache dependencies across rules

maven-enforcer-extension/pom.xml, maven-enforcer-plugin/pom.xml
=> [MENFORCER-421] Use currently build artifacts in IT tests

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireReleaseDeps.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireReleaseDeps.java
=> [MENFORCER-389] Allow filtering of parent in requireReleaseDeps

enforcer-api/src/custom-rule-sample/pom.xml, enforcer-api/src/site/apt/writing-a-custom-rule.apt.vm
=> [MENFORCER-425] clarify class loading of custom rules

maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java, maven-enforcer-plugin/src/test/java/org/apache/maven/plugins/enforcer/TestEnforceMojo.java
Hi there,
this fixes [MENFORCER-398](https://issues.apache.org/jira/browse/MENFORCER-398). It is a simple one line change. Turning on DEBUG already logs what rules are processed. Since most people probably run Maven in default settings they won't see the rules processed. Changing the log level from DEBUG to INFO allows everyone to see the rule processed.
This is an up-for-grabs issue. Feedback welcome.
be …
=> [MENFORCER-398] show rules processed

maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java, maven-enforcer-plugin/src/test/java/org/apache/maven/plugins/enforcer/TestEnforceMojo.java
Hi there,
attached is another `up-for-grabs`. This PR allows no rules by adding a `failIfNoRules` parameter. Settings `failIfNoRules` to false will log a warning "No rules are configured" instead of throwing an exception. Default behaviour is to throw an exception if there are no rules configured. Like people are used to.
A suitable test case has been added.
Feedback is welcome.
is to use the JIRA issue title in the pull …
=> [MENFORCER-397] allow no rules

.gitignore, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/EnforcerDescriptor.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/ExternalRules.java, enforcer-rules/src/site/apt/externalRules.apt.vm, enforcer-rules/src/site/apt/index.apt, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/EnforcerTestUtils.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestExternalRules.java, enforcer-rules/src/test/resources/enforcer-rules/pass.xml, maven-enforcer-plugin/src/it/projects/external-rules-always-fail/enforcer-rules.xml, maven-enforcer-plugin/src/it/projects/external-rules-always-fail/invoker.properties, maven-enforcer-plugin/src/it/projects/external-rules-always-fail/pom.xml, maven-enforcer-plugin/src/it/projects/external-rules-always-pass/enforcer-rules.xml, maven-enforcer-plugin/src/it/projects/external-rules-always-pass/pom.xml, pom.xml
=> [MENFORCER-422] Added externalRules rule

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractRequireFiles.java, enforcer-rules/src/site/apt/requireFilesDontExist.apt.vm, enforcer-rules/src/site/apt/requireFilesExist.apt.vm, enforcer-rules/src/site/apt/requireFilesSize.apt.vm, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFilesDontExist.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFilesExist.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireFilesSize.java
This PR resolves the issue [MENFORCER-430](https://issues.apache.org/jira/browse/MENFORCER-430?jql=project%20%3D%20MENFORCER).
Given a list of files it was not possible to enforce only a list where only one filed would be sufficient.
For example check if one of the following files exists:
* README
* README.md
* README.adoc
A new paramenter `satisfyAny` was added to `AbstractRequiresFiles`. If `satisfyAny` is `true` then it is enough if one of the files passes the check. 
This PR affects the following built-in rules:
* RequireFilesDontExist
* RequireFilesExist
* RequireFilesSize
Tests have been added.
I do not know if the [documentation of the builtin-rules](https://maven.apache.org/enforcer/enforcer-rules/requireFilesExist.html) updates itself with the new paramenter `satisfyAny` or if I …
=> [MENFORCER-430] Allow one of many files in RequireFiles rules to pass

enforcer-rules/pom.xml, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractBanDependencies.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanDynamicVersions.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanTransitiveDependencies.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BannedDependencies.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BannedDependenciesBase.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BannedPlugins.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/DependencyConvergence.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequirePluginVersions.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireReleaseDeps.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireUpperBoundDeps.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/ArtifactMatcher.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/ArtifactUtils.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/DependencyVersionMap.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/EnforcerRuleUtils.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/ParentNodeProvider.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/utils/ParentsVisitor.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/BannedDependenciesTestSetup.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/EnforcerTestUtils.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireReleaseDeps.java, maven-enforcer-plugin/src/it/projects/banned-dependencies-fail/invoker.properties, maven-enforcer-plugin/src/it/projects/banned-dependencies-fail/pom.xml, maven-enforcer-plugin/src/it/projects/banned-dependencies-fail/verify.groovy, maven-enforcer-plugin/src/it/projects/multimodule-ban-transitive-dependencies_failure/verify.groovy, maven-enforcer-plugin/src/it/projects/multimodule-require-release-dependencies-exclude_failure/verify.groovy
See summary; also: dependency:tree is no longer necessary to check parent information of dependencies which triggered validation failures -- path information is included.
@slawekjaranowski please review
=> [MENFORCER-435] Replacing maven-compat and maven-dependency-tree usage with Resolver

enforcer-rules/pom.xml, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BanTransitiveDependencies.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/BannedDependenciesBase.java, maven-enforcer-extension/pom.xml, maven-enforcer-plugin/pom.xml, pom.xml
=> [MENFORCER-452] Manage all Maven Core dependencies as provided

maven-enforcer-plugin/src/it/projects/cli-skip-rules/invoker.properties, maven-enforcer-plugin/src/it/projects/cli-skip-rules/pom.xml, maven-enforcer-plugin/src/it/projects/cli-skip-rules/verify.groovy, maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java
I am creating this draft PR to discuss couple of points. This is not yet ready to merge. See the inline comments.
To make clear that you license your …
=> [MENFORCER-431] Introduce option to skip specific rules via custom property

maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java, maven-enforcer-plugin/src/test/java/org/apache/maven/plugins/enforcer/TestEnforceMojo.java
* the method gets called with empty list if there is no configuration, resulting in WARNing being printed every single time.
* it somehow slipped in and I only noticed this after merging the main PR. …
=> [MENFORCER-454] Log warning only if the '-Drules' is actually used

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVendor.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVersion.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVendor.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVersion.java
=> [MENFORCER-445] Include JAVA_HOME location in the Java rule failure messages

enforcer-api/src/site/apt/writing-a-custom-rule.apt.vm
=> [MENFORCER-425] Clarify usage of maven-enforcer-rules

enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/AbstractVersionEnforcer.java, enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVersion.java, enforcer-rules/src/test/java/org/apache/maven/plugins/enforcer/TestRequireJavaVersion.java
Convert lower bound only value to proper range string in message …
=> [MENFORCER-444] Improve error message for failed version rules

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/checksum/NormalizeLineSeparatorReader.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/checksum/RequireFileChecksum.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/checksum/RequireTextFileChecksum.java, enforcer-rules/src/site/apt/requireFileChecksum.apt.vm, enforcer-rules/src/site/apt/requireTextFileChecksum.apt.vm, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/checksum/TestNormalizeLineSeparatorReader.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/checksum/TestRequireFileChecksum.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/checksum/TestRequireTextFileChecksum.java, maven-enforcer-plugin/src/it/projects/require-file-checksum/verify.groovy, maven-enforcer-plugin/src/it/projects/require-textfile-checksum/LICENSE, maven-enforcer-plugin/src/it/projects/require-textfile-checksum/pom.xml, maven-enforcer-plugin/src/it/projects/require-textfile-checksum/verify.groovy
=> [MENFORCER-458] Move Require*Checksum to new API

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/property/AbstractPropertyEnforcerRule.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/property/RequireEnvironmentVariable.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/property/RequireProperty.java, enforcer-rules/src/site/apt/requireEnvironmentVariable.apt.vm, enforcer-rules/src/site/apt/requireProperty.apt.vm, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/property/TestRequireEnvironmentVariable.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/property/TestRequireProperty.java, maven-enforcer-plugin/src/it/projects/require-environment-variable/pom.xml, maven-enforcer-plugin/src/it/projects/require-environment-variable/verify.groovy, maven-enforcer-plugin/src/it/projects/require-property/verify.groovy
=> [MENFORCER-458] Move Require Property,Environment to new API

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequirePluginVersions.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequirePluginVersions.java, enforcer-rules/src/test/resources/requirePluginVersions/checkPluginVersionProfile/pom.xml, maven-enforcer-plugin/src/it/projects/require-plugin-versions-ci/verify.groovy, maven-enforcer-plugin/src/it/projects/require-plugin-versions/pom.xml, maven-enforcer-plugin/src/it/projects/require-plugin-versions_failure/verify.groovy
And a little error message improvement
---
To make clear that you …
=> [MENFORCER-461] Fix NPE in RequirePluginVersions

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/ReactorModuleConvergence.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/ReactorModuleConvergenceTest.java
Rule checks whole reactor of current build so can be executed once in session
---
please ask on the …
=> [MENFORCER-462] Execute ReactorModuleConvergence only once

enforcer-api/src/site/site.xml, enforcer-rules/src/site/site.xml, maven-enforcer-extension/src/site/site.xml, maven-enforcer-plugin/src/site/apt/examples/check-specific-rule-via-cli.apt.vm, maven-enforcer-plugin/src/site/site.xml, src/site/site.xml
- update shames to 1.8.0
- use https for licence
- add links to download and license in all modules
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
=> [MENFORCER-464] Refresh site descriptors

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolveUtil.java, maven-enforcer-plugin/src/it/projects/require-upper-bound-deps-provided/invoker.properties, maven-enforcer-plugin/src/it/projects/require-upper-bound-deps-provided/pom.xml
Following a regression indicated in https://issues.apache.org/jira/browse/MENFORCER-466, scope should exclude provided. 
In this PR, if no other dependency exclusions are set, I'm applying the default dependency exclusions as are present in `MavenRepositorySystemUtils.newSession()`,
namely:
```java
new AndDependencySelector( new ScopeDependencySelector( "test", "provided" ),
new OptionalDependencySelector(), new ExclusionDependencySelector() );
```
@slawekjaranowski please review
where you replace …
=> [MENFORCER-466] Changed the default set of dependency exclusions to exclude provided

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/DependencyConvergence.java, enforcer-rules/src/site/apt/dependencyConvergence.apt.vm
After the release of v3.2 of the plugin, I discovered some breaking changes in API, thus had problems migrating my rule https://github.com/alexey-anufriev/advanced-enforcer-rules to a new version along with the support of the previous plugin versions.
For this reason, I have reimplemented the missing features directly in the original rule.
---
is to use the JIRA issue title in the pull request title and in the first line of …
=> [MENFORCER-470] AdvancedDependencyConvergence rule

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanTransitiveDependencies.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BannedDependencies.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BannedDependenciesBase.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/DependencyConvergence.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/RequireReleaseDeps.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDeps.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolverUtil.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/BannedDependenciesTest.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireReleaseDepsTest.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/dependency/RequireUpperBoundDepsTest.java
=> [MENFORCER-476] Rename ResolveUtil to ResolverUtil

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanDynamicVersions.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolverUtil.java, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions/verify.groovy
We should not change default Maven scope filtering for transitive dependencies
---
Put message of violation into exception to be consistent with other rules
[Individual Contributor License …
=> [MENFORCER-467] banDynamicVersions excludedScopes on project level

enforcer-rules/src/site/apt/banDynamicVersions.apt.vm
fix wrong description of allowRanges
add JIRA link for allowRangesWithIdenticalBounds
clarify excludedScopes
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
=> improve documentation of banDynamicVersions

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanDynamicVersions.java, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions-scope-all-scopes/invoker.properties, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions-scope-all-scopes/pom.xml, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions-scope-all-scopes/verify.groovy
Suggested commit message:
```
[MENFORCER-481] BanDynamicVersions: make `excludedScopes` optional
With these changes, omission of `excludedScopes` no longer causes an NPE.
```
=> [MENFORCER-481] BanDynamicVersions: make `excludedScopes` optional

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanDynamicVersions.java, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions/pom.xml, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions/verify.groovy
Suggested commit message:
```
[MENFORCER-480] BanDynamicVersions: fix `ignores` parameter
Matching artifacts should be _excluded_ rather than included.
```
=> [MENFORCER-480] BanDynamicVersions: fix `ignores` parameter

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BannedRepositories.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/EvaluateBeanshell.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireActiveProfile.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireOS.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequirePluginVersions.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/version/AbstractVersionEnforcer.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/version/RequireJavaVersion.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
If your pull request …
=> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

maven-enforcer-plugin/src/it/mrm/repository/menforcer426-a-1.0.pom, maven-enforcer-plugin/src/it/mrm/repository/menforcer426-b-1.0.pom, maven-enforcer-plugin/src/it/projects/dependency-convergence-ranges/invoker.properties, maven-enforcer-plugin/src/it/projects/dependency-convergence-ranges/pom.xml
=> [MENFORCER-426] DependencyConvergence transitive dependencies with version range

enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/AbstractEnforcerRule.java, enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/AbstractEnforcerRuleBase.java, enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/AbstractEnforcerRuleConfigProvider.java, enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/EnforcerLogger.java, enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/EnforcerRuleBase.java, enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/EnforcerRuleError.java, enforcer-api/src/site/apt/writing-a-custom-rule.apt.vm
Improve links to javadoc
Fix some typos
=> Clarify availability of AbstractEnforcerRule

maven-enforcer-plugin/src/site/apt/index.apt
=> Oxford comma, fill to file, and tighten language

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/BanDynamicVersions.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/dependency/ResolverUtil.java, enforcer-rules/src/site/apt/banDynamicVersions.apt.vm, maven-enforcer-plugin/src/it/mrm/repository/menforcer494_dependency-1.0-SNAPSHOT.pom, maven-enforcer-plugin/src/it/mrm/repository/menforcer494_dependency-2.0.pom, maven-enforcer-plugin/src/it/mrm/repository/menforcer494_project-1.0-SNAPSHOT.pom, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions-verbose/invoker.properties, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions-verbose/pom.xml, maven-enforcer-plugin/src/it/projects/ban-dynamic-versions-verbose/verify.groovy
This commit introduces the possibility of banning dynamic versions in the entire dependency tree before Maven computes the final dependency tree. If a dependency exists multiple times in the dependency tree the plugin will not detect any dynamic versions as long as the final dependency tree does not have any dynamic versions.
In this example the dependency `A -> C -> D` is not detected with a dynamic version unless the `verbose` parameter has been set in this pull request.
```
A
+- B
|  \- D version 1.0
\- C
\- D version [1.0,2.0)
```
require a JIRA issue.  Your pull request should address just this issue, …
=> [MENFORCER-494] Allow banning dynamic versions in whole tree

maven-enforcer-extension/pom.xml
ITs passed locally so this doesn't appear to be needed. 
If it is needed we'll need to figure out how to properly exclude this from the dependency analyzer
=> [MENFORCER-490] Remove unused dependency

maven-enforcer-plugin/src/it/projects/cli-banned-plugins/invoker.properties, maven-enforcer-plugin/src/it/projects/cli-banned-plugins/pom.xml, maven-enforcer-plugin/src/it/projects/cli-banned-plugins/verify.groovy, maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/EnforceMojo.java, maven-enforcer-plugin/src/site/apt/examples/check-specific-rule-via-cli.apt.vm
This will allow the enforcer to utilize rule configuration defined in the project POM when the rule is run explicitly from the command line, e.g. `mvn enforcer:enforce -Denforcer.rules=requireReleaseDeps`.
Following this checklist to help us incorporate your contribution quickly and easily: …
=> [MENFORCER-516] Use rule configuration in POM when executed from CLI

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequireSameVersions.java, enforcer-rules/src/test/java/org/apache/maven/enforcer/rules/TestRequireSameVersions.java, maven-enforcer-plugin/src/it/projects/require-same-versions_failure/verify.groovy
Resolves #372 
if plugins are analyzed, entries under `<plugins>` must be considered f
=> `RequireSameVersions` rule: consider entries in `<plugins>`  when analyzing build- and report-plugins

enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/AbstractEnforcerRule.java, enforcer-api/src/main/java/org/apache/maven/enforcer/rule/api/EnforcerRuleBase.java, enforcer-rules/src/site/apt/alwaysPass.apt.vm, enforcer-rules/src/site/apt/index.apt, maven-enforcer-plugin/src/it/projects/always-fail-warn/pom.xml, maven-enforcer-plugin/src/it/projects/always-fail-warn/verify.groovy, maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/internal/EnforcerRuleDesc.java
We can define the same rule multiple times with different configuration
Each execution has the same default name, with ruleName we can differentiate them
=> Introduce ruleName for rules configuration

enforcer-api/src/custom-rule-sample/pom.xml, enforcer-api/src/custom-rule-sample/src/main/java/org/example/custom/rule/MyCustomRule.java
- use constructor for components injection
- use a sisu version from the project
=> Improve example of custom rule

maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/internal/EnforcerRuleManager.java
external rules should use a new enforcer api
=> Warning about old enforcer api in rule implementation

enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/BannedRepositories.java, enforcer-rules/src/main/java/org/apache/maven/enforcer/rules/RequirePluginVersions.java
Account for variables that are guaranteedly null or non-null.
=> null analysis

enforcer-rules/src/site/apt/dependencyConvergence.apt.vm
Fixes a small typo in the APT markup for one of the rule descriptions that becomes unreadable on my phone.
<small>Apache CLA has been signed and sent in via email for previous contributions.</small>
=> Fix formatting typo in dependencyConvergence.apt.vm

maven-enforcer-plugin/src/it/projects/require-java-vendor-multi-module/invoker.properties, maven-enforcer-plugin/src/main/java/org/apache/maven/plugins/enforcer/internal/EnforcerRuleCache.java
Each Maven session should have a new cache.
Singleton can be shared between executions by Maven Daemon.
=> Use SessionData for cache storage

enforcer-rules/src/site/apt/versionRanges.apt, maven-enforcer-plugin/src/site/site.xml
Remove link to outdated confluence page about version ranges, and use a link to a page on maven-enforcer's site instead.
This fixes #906 
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge …
=> Update Version Ranges link in site.xml
